# Site settings
title: Campus Guide - University of Ottawa
email: contact@josephroque.ca
description: > # this means to ignore newlines until "baseurl:"
  An app to help students at the University of Ottawa learn more about their campus,
  get involved, and stay organized.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://campusguide.ca" # the base hostname & protocol for your site
twitter_username: josephroqueca
github_username:  josephroqueca
author: Joseph Roque

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from